// Nur timeline-eigene Formulierungen. „Timeline“, „Zeitpunkt“, „Beziehung“, „Gerichtet“ und
// die Zeitpunkt-Aktionen stehen in shared.ts, weil Figuren- und Ortsbereich sie mitbenutzen.
export const timeline = {
  timelineUndo: 'Timeline rückgängig', timelineRedo: 'Timeline wiederholen',
  timelineEmptyTitle: 'Noch keine Timeline', timelineEmptyHelp: 'Ein Zeitpunkt hält fest, was sich ab dort in der Welt ändert.', timelineFirst: 'Ersten Zeitpunkt anlegen',
  timelineInsertStart: 'Zeitpunkt am Anfang einfügen', timelineInsertAfter: 'Zeitpunkt nach {title} einfügen', timelinePrevious: 'Vorheriger Zeitpunkt', timelineNext: 'Nächster Zeitpunkt', timelineOf: '{current} von {total}', timelinePoint: 'Zeitpunkt {number}', timelineOwnChanges: '{count} eigene Änderungen. Spätere Zeitpunkte erben diesen Stand.',
  timelineEarlier: 'Früher', timelineLater: 'Später', timelineActions: 'Zeitpunktaktionen', timelineDuplicate: 'Zeitpunkt duplizieren', timelineNotePlaceholder: 'Was sich ab hier ändert', timelineView: 'Beziehungsansicht', timelineRelationshipView: 'Angezeigte Beziehungen', timelineOnlyChanges: 'Nur Änderungen', timelineWholeState: 'Alle Beziehungen',
  timelineRelationsChanged: 'Beziehungen, die sich genau hier ändern.', timelineRelationsState: 'Der an diesem Zeitpunkt gültige Stand aller Beziehungen.', timelineChangeRelation: 'Beziehung ändern …', timelineNoLabel: 'ohne Bezeichnung', timelineNoRelationChanges: 'An diesem Zeitpunkt ändert sich keine Beziehung.',
  timelinePresence: 'Anwesenheit', timelinePresenceHelp: 'Ziehe Figuren auf einen Ort. Der Ort gilt ab hier weiter.', timelineLife: 'Lebensereignisse', timelineLifeHelp: 'Ziehe eine Figur oder ein Tier auf die Ereignisfläche oder wähle beides nacheinander.', timelineDeathHere: 'Stirbt an diesem Zeitpunkt', timelineDeathSelected: 'Klicken, um das gewählte Element zuzuordnen', timelineDeathHelp: 'Figur hier ablegen oder zuerst auswählen',
  timelineDeleteDescription: '„{title}“ und {count} eigene Änderungen werden entfernt. Spätere Zeitpunkte erben dadurch einen anderen Stand.', deleteTimeMomentDescription: '„{title}“ wird aus der Timeline entfernt. Beziehungsänderungen an diesem Zeitpunkt fallen auf den vorherigen Stand zurück.',
  timelineCloseRelation: 'Beziehungs-Inspector schließen', timelineLabelFromHere: 'Bezeichnung ab hier', timelineInherited: 'Geerbt: {value}', timelineAppliesHere: 'Gilt ab hier', timelineEndsHere: 'Endet hier', timelineRemoveOwn: 'Eigene Änderung entfernen', timelineInheritPrevious: 'Vorherigen Stand wieder erben', timelineInheritedHelp: 'Dieser Stand kommt vom vorherigen Zeitpunkt. Eine Bearbeitung legt hier eine eigene Änderung an.', timelineChange: 'Änderung', timelineInheritedBadge: 'Geerbt', timelineWithoutLabel: 'Ohne Bezeichnung', timelineChangedLabel: '{before} → {after}',
  timelineStripLabel: 'Beziehungen über die Zeit', pauseTimeTravel: 'Zeitreise pausieren', playTimeTravel: 'Zeitreise abspielen', overview: 'Gesamtsicht', newMomentDate: 'Datum des neuen Zeitpunkts', momentNotePlaceholder: 'Kapitel, Zeitsprung, Ereignis …', timeToggle: 'Zeit',
  noFiguresOrAnimalsYet: 'Noch keine Figuren oder Tiere.', noPlacesInBoard: 'Noch keine Orte im Figurenboard.', active: 'Aktiv',
  unchangedNoPlace: 'Unverändert / kein Ort', figuresAndAnimalsListLabel: 'Figuren und Tiere', inheritedFrom: 'geerbt · {name}',
} as const;
