export const timeline = {
  deleteTimeMoment: 'Zeitpunkt löschen', momentKind: 'Zeitpunkt',
  deleteTimeMomentDescription: '„{title}“ wird aus dem Zeitstreifen entfernt. Beziehungsänderungen an diesem Zeitpunkt fallen auf den vorherigen Stand zurück.', deleteMomentDescription: '„{title}“ und die dort gespeicherten Zustandsänderungen werden entfernt. Halte den Löschknopf fünf Sekunden gedrückt.',
  timelineStripLabel: 'Beziehungs-Zeitstreifen', pauseTimeTravel: 'Zeitreise pausieren', playTimeTravel: 'Zeitreise abspielen', overview: 'Gesamtsicht', newMoment: 'Neuer Zeitpunkt', newMomentDate: 'Datum des neuen Zeitpunkts', addMoment: 'Zeitpunkt hinzufügen', optionalDate: 'Datum · optional', optionalNote: 'Notiz · optional', momentNotePlaceholder: 'Kapitel, Zeitsprung, Ereignis …', timeToggle: 'Zeit',
  timelineManageLabel: 'Timeline verwalten', moments: 'Zeitpunkte', undoTimeline: 'Timeline rückgängig', redoTimeline: 'Timeline wiederholen', noDate: 'Kein Datum', noTimelineYet: 'Noch keine Timeline',
  timelineIntro: 'Zeitpunkte bilden die Zustände deiner Welt ab. Die Reihenfolge hier steuert auch die Animation im Figurenboard.', createMoment: 'Zeitpunkt anlegen', createFirstMoment: 'Ersten Zeitpunkt anlegen', emptyTimelineHint: 'Lege den ersten Zeitpunkt an, um Beziehungen über die Zeit zu verwalten.',
  momentNumberLabel: 'Zeitpunkt {n}', changesAtMoment: '{n} Änderungen an diesem Zeitpunkt', moveEarlierHelp: 'Früher einordnen', moveLaterHelp: 'Später einordnen', earlier: 'Früher', later: 'Später', momentNoteQuestion: 'Was verändert sich an diesem Zeitpunkt?',
  relationshipsSectionDescription: 'Hier änderst du ausschließlich den Zustand am ausgewählten Zeitpunkt.', lifeEventsSection: 'Lebensereignisse', lifeEventsSectionDescription: 'Markiere, welche Figuren oder Tiere an diesem Zeitpunkt sterben.', presenceSection: 'Anwesenheit', presenceSectionDescription: 'Ziehe eine Figur oder ein Tier auf einen Ort, um die Anwesenheit an diesem Zeitpunkt zu setzen.',
  noRelationshipsInBoard: 'Noch keine Beziehungen im Figurenboard.', noFiguresOrAnimalsYet: 'Noch keine Figuren oder Tiere vorhanden.', active: 'Aktiv', reverseDirectionBetween: 'Richtung zwischen {from} und {to} umkehren', reverseDirection: 'Richtung umkehren', undirected: 'Ungerichtet', labelForXAndY: 'Bezeichnung für {from} und {to}', relationshipWord: 'Beziehung',
  unchangedNoPlace: 'Unverändert / kein Ort', figuresAndAnimalsListLabel: 'Figuren und Tiere', inheritedFrom: 'geerbt · {name}', noPlacesInBoard: 'Noch keine Orte im Figurenboard.',
} as const;
