export const tools = {
  searchCommands: 'Suchen & Befehle', searchPlaceholder: 'Kapitel, Text, Figuren, Orte …', command: 'Befehl',
  snapshotSave: 'Arbeitsstand sichern', target: 'Ziel', changed: 'Geändert', files: 'Dateien', notConfigured: 'Nicht eingerichtet', snapshotMessage: 'Was hat sich geändert?', saveOnly: 'Nur lokal sichern', saveAndUpload: 'Sichern & hochladen', technicalDetails: 'Technische Details',
  loadingBackupStatus: 'Status wird geladen …', done: 'Fertig.',
  backupSignIn: 'Bei der Sicherung anmelden', backupSignInHint: 'Das Ziel ist eingerichtet, aber noch nicht angemeldet. Zum Hochladen ist eine Anmeldung im Browser nötig.', backupSignInWaiting: 'Warten auf die Anmeldung im Browserfenster …', backupSignInFailed: 'Die Anmeldung konnte nicht begonnen werden.', backupSessionExpired: 'Diese Sitzung hat kein gültiges Token für das Sicherungsziel mehr. Melde dich einmal ab und wieder an.', backupIssuerChecking: 'Der Anmeldedienst des Ziels wird gerade geprüft …', backupIssuerUnreachable: 'Der Anmeldedienst des Ziels antwortet gerade nicht. Eine Anmeldung ist erst wieder möglich, wenn er erreichbar ist.', backupAccount: 'Konto', backupSignedIn: 'Angemeldet',
  comparison: 'Vergleich', byWord: 'Wortweise', byLine: 'Zeilenweise', allFiles: 'Alle Dateien', textOnly: 'Nur Text', states: 'Stände', sinceCommit: 'Seit letzter Sicherung', workingState: 'Arbeitsstand', noChanges: 'Keine Änderungen', newFiles: 'Neue Dateien',
  database: 'Datenbank', statWords: '+{added} / -{removed} Wörter', statLines: '+{added} / -{removed} Zeilen', binaryChange: 'Geändert, Inhalt wird hier nicht angezeigt.',
  restore: 'Wiederherstellen', restoreBackup: 'Sicherung wiederherstellen', noBackup: 'Noch keine Sicherung vorhanden.', backupAutoNote: 'SQLite-Sicherungen entstehen automatisch, höchstens alle fünf Minuten.', restoreConfirmDescription: 'Der aktuelle Stand wird zunächst gesichert und anschließend vollständig durch diese Sicherung ersetzt.', backupPreviewDescription: 'Lokale SQLite-Sicherung · {size}', backupSelectTitle: 'Sicherung auswählen', backupSelectDescription: 'Wähle links eine Sicherung, um sie zu prüfen und wiederherzustellen.',
  switchToManuscript: 'Zum Manuskript wechseln', switchToFigures: 'Zum Figurenboard wechseln', switchToTimeline: 'Zur Timeline wechseln', switchToPlaces: 'Zu Orten wechseln', toggleFocus: 'Fokusmodus umschalten', noSearchResults: 'Keine passenden Inhalte oder Befehle gefunden.',
} as const;
