"""Hatch build hook that embeds the Python distribution contract.

The checked-in profile beside ``runtime_target.py`` describes a source checkout
and is deliberately excluded from package artifacts.  Wheel and sdist builds
materialize ``python-package`` from the same declarative source used by every
other distribution target and force-include those exact generated bytes.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

from hatchling.builders.hooks.plugin.interface import BuildHookInterface

TOOLING_ROOT = Path(__file__).resolve().parent
if str(TOOLING_ROOT) not in sys.path:
    sys.path.insert(0, str(TOOLING_ROOT))

from profile_contract import materialize_profile  # noqa: E402

MCP_SOURCE_PATH = Path("contracts/fixtures/mcp/tools.v1.json")


class CustomBuildHook(BuildHookInterface):
    """Embed a deterministic target contract in every Python package artifact."""

    PLUGIN_NAME = "custom"

    def initialize(self, version: str, build_data: dict[str, object]) -> None:
        root = Path(self.root)
        force_include = build_data["force_include"]
        if not isinstance(force_include, dict):
            raise RuntimeError("Hatch did not provide a force-include mapping.")
        # `python -m build` intentionally builds the wheel from the just-created
        # sdist. The wheel target consumes the source contract at its canonical
        # repository path, so the sdist must retain that path in addition to its
        # packaged resource copy. A direct wheel build alone would hide this.
        if self.target_name == "sdist":
            source_contract = root / MCP_SOURCE_PATH
            preserved_contract = (
                root / "distribution/.build/python-package/source-contract/tools.v1.json"
            )
            preserved_contract.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source_contract, preserved_contract)
            force_include[str(preserved_contract)] = MCP_SOURCE_PATH.as_posix()
        elif (root / "src/quiltor/resources/contracts/mcp/tools.v1.json").is_file():
            # A wheel built from our sdist already discovers the packaged copy
            # through the `src/quiltor` package tree. Keeping the checkout-only
            # force-include as well would add the same archive member twice.
            configured_force_include = self.build_config.target_config.get("force-include")
            if isinstance(configured_force_include, dict):
                configured_force_include.pop(MCP_SOURCE_PATH.as_posix(), None)
            # Hatchling memoizes the normalized target mapping. Drop a possible
            # earlier value so the adjusted configuration is read for this build.
            self.build_config.__dict__.pop("force_include", None)
        generated = root / "distribution/.build/python-package/quiltor-build-profile.json"
        materialize_profile("python-package", generated, repo_root=root)
        suffix = "quiltor/infrastructure/platform/quiltor-build-profile.json"
        destination = f"src/{suffix}" if self.target_name == "sdist" else suffix
        force_include[str(generated)] = destination
