// Timeline-only wording. “Timeline”, “moment”, “relationship”, “directed” and the moment
// actions live in shared.ts because the character and place areas use them too.
export const timeline = {
  timelineUndo: 'Undo timeline change', timelineRedo: 'Redo timeline change',
  timelineEmptyTitle: 'No timeline yet', timelineEmptyHelp: 'A moment records what changes in the world from that point on.', timelineFirst: 'Create first moment',
  timelineInsertStart: 'Insert moment at the beginning', timelineInsertAfter: 'Insert moment after {title}', timelinePrevious: 'Previous moment', timelineNext: 'Next moment', timelineOf: '{current} of {total}', timelinePoint: 'Moment {number}', timelineOwnChanges: '{count} own changes. Later moments inherit this state.',
  timelineEarlier: 'Earlier', timelineLater: 'Later', timelineActions: 'Moment actions', timelineDuplicate: 'Duplicate moment', timelineNotePlaceholder: 'What changes from here', timelineView: 'Relationship view', timelineRelationshipView: 'Relationships shown', timelineOnlyChanges: 'Changes only', timelineWholeState: 'All relationships',
  timelineRelationsChanged: 'Relationships that change at this exact moment.', timelineRelationsState: 'The state of all relationships at this moment.', timelineChangeRelation: 'Change relationship …', timelineNoLabel: 'without label', timelineNoRelationChanges: 'No relationship changes at this moment.',
  timelinePresence: 'Presence', timelinePresenceHelp: 'Drag characters onto a place. The place carries forward from here.', timelineLife: 'Life events', timelineLifeHelp: 'Drag a character or animal onto the event area, or select both in sequence.', timelineDeathHere: 'Dies at this moment', timelineDeathSelected: 'Click to assign the selected element', timelineDeathHelp: 'Drop a character here or select one first',
  timelineDeleteDescription: '“{title}” and {count} own changes will be removed. Later moments will inherit a different state as a result.', deleteTimeMomentDescription: '“{title}” will be removed from the timeline. Relationship changes at this moment fall back to the previous state.',
  timelineCloseRelation: 'Close relationship inspector', timelineLabelFromHere: 'Label from here', timelineInherited: 'Inherited: {value}', timelineAppliesHere: 'Applies from here', timelineEndsHere: 'Ends here', timelineRemoveOwn: 'Remove own change', timelineInheritPrevious: 'Inherit the previous state again', timelineInheritedHelp: 'This state comes from the previous moment. Editing it creates an own change here.', timelineChange: 'Change', timelineInheritedBadge: 'Inherited', timelineWithoutLabel: 'Without label', timelineChangedLabel: '{before} → {after}',
  timelineStripLabel: 'Relationships over time', pauseTimeTravel: 'Pause time travel', playTimeTravel: 'Play time travel', overview: 'Overview', newMomentDate: 'Date of the new moment', momentNotePlaceholder: 'Chapter, time jump, event …', timeToggle: 'Time',
  noFiguresOrAnimalsYet: 'No characters or animals yet.', noPlacesInBoard: 'No places in the character board yet.', active: 'Active',
  unchangedNoPlace: 'Unchanged / no place', figuresAndAnimalsListLabel: 'Characters and animals', inheritedFrom: 'inherited · {name}',
} as const;
