export const tools = {
  searchCommands: 'Search & commands', searchPlaceholder: 'Chapters, text, characters, places …', command: 'Command',
  snapshotSave: 'Save working state', target: 'Target', changed: 'Changed', files: 'files', notConfigured: 'Not configured', snapshotMessage: 'What changed?', saveOnly: 'Save locally only', saveAndUpload: 'Save & upload', technicalDetails: 'Technical details',
  loadingBackupStatus: 'Loading status …', done: 'Done.',
  backupSignIn: 'Sign in for backups', backupSignInHint: 'The target is configured, but not signed in yet. Uploading needs a sign-in in the browser.', backupSignInWaiting: 'Waiting for the sign-in in the browser window …', backupSignInFailed: 'The sign-in could not be started.', backupIssuerUnreachable: 'The sign-in service for this target is not answering right now. Signing in is only possible once it can be reached again.', backupAccount: 'Account', backupSignedIn: 'Signed in',
  comparison: 'Comparison', byWord: 'By word', byLine: 'By line', allFiles: 'All files', textOnly: 'Text only', states: 'States', sinceCommit: 'Since last save', workingState: 'Working state', noChanges: 'No changes', newFiles: 'New files',
  database: 'Database', statWords: '+{added} / -{removed} words', statLines: '+{added} / -{removed} lines', binaryChange: 'Changed, content not shown here.',
  restore: 'Restore', restoreBackup: 'Restore backup', noBackup: 'No backup available yet.', backupAutoNote: 'SQLite backups are created automatically, at most every five minutes.', restoreConfirmDescription: 'The current state is backed up first, then completely replaced by this backup.', backupPreviewDescription: 'Local SQLite backup · {size}', backupSelectTitle: 'Select a backup', backupSelectDescription: 'Select a backup on the left to review and restore it.',
  switchToManuscript: 'Switch to manuscript', switchToFigures: 'Switch to character board', switchToTimeline: 'Switch to timeline', switchToPlaces: 'Switch to places', toggleFocus: 'Toggle focus mode', noSearchResults: 'No matching content or commands found.',
} as const;
