// Fictional author material for reproducible screenshots of the real application.

export const manuscript = {
  chapters: [
    {
      id: "c-arrival",
      title: "Die Ankunft",
      body: "Der Morgen lag still über dem Hafen. Zwischen den Masten schimmerte das Archiv wie eine Erinnerung aus Glas.\n\nMara blieb am Ende des Stegs stehen. Heute würde sie erfahren, weshalb die Karten seit drei Nächten ihre Linien veränderten.\n\nUnter ihrem Mantel trug sie das letzte Blatt aus dem Nachlass ihres Vaters. Die Küstenlinie darauf endete nicht am Meer. Sie führte weiter, als hätte jemand einen Weg durch das Wasser gezeichnet.\n\nAm Tor des Gezeitenarchivs löste sich ein Mann aus dem Schatten. Er hielt keine Lampe, obwohl die Fenster hinter ihm dunkel waren.\n\n»Du bist spät«, sagte Iven Rook.\n\nMara betrachtete die Salzspuren auf seinen Stiefeln. »Du hast auf jemand anderen gewartet.«\n\nEr antwortete nicht. Über dem Hafen schlug die erste Glocke, und auf dem Blatt in ihrer Tasche verschob sich eine Linie.",
      note: "Die Unruhe der Stadt nur andeuten. Das Archiv als stillen Gegenpol etablieren.",
      storyTime: {
        startMomentId: "t1",
      },
    },
    {
      id: "c-archive",
      title: "Das Archiv",
      body: "Im Lesesaal wartete bereits der Hüter der Karten. Auf dem langen Tisch lag ein Atlas, dessen Seiten dünner waren als Eis.\n\nIven legte Maras Blatt neben die erste Karte. Beide Küstenlinien begannen zu leuchten. Draußen zogen Wolken über den Hafen, doch hier fiel das Licht von unten durch das Glas.",
      note: "Erstes Zusammentreffen mit der Kartographengilde.",
      storyTime: {
        startMomentId: "t2",
      },
    },
    {
      id: "c-storm",
      title: "Vor dem Sturm",
      body: "Der Hafenrat hatte die Brücken sperren lassen. Nur am Gezeitenarchiv brannte noch Licht. Mara wusste nun, dass die Gilde nicht nach einer verlorenen Route suchte. Sie wollte verhindern, dass jemand sie fand.",
      note: "Konflikt zwischen Gilde und Hafenrat zuspitzen.",
      storyTime: {
        startMomentId: "t3",
      },
    },
    {
      id: "c-crossing",
      title: "Die Überfahrt",
      body: "Bei Tagesanbruch lösten sie die Leinen. Hinter ihnen versank die Leuchtturmklippe im Nebel. Vor ihnen zeigte der Atlas zum ersten Mal eine offene Küste.",
      note: "",
      storyTime: {
        startMomentId: "t4",
      },
    },
  ],
  words: [
    {
      w: "Lichtsaum",
      d: "Schimmernde Grenze auf alten Karten",
    },
    {
      w: "Gezeitenarchiv",
      d: "Zentrales Archiv der Stadt",
    },
  ],
  activeSymbols: ["…", "—", "»", "«"],
  structure: {
    folders: [
      {
        id: "act-one",
        title: "I · Nordhafen",
      },
      {
        id: "act-two",
        title: "II · Kartennebel",
      },
    ],
    items: [
      {
        id: "folder-one",
        kind: "folder",
        folderId: "act-one",
        position: 0,
      },
      {
        id: "folder-two",
        kind: "folder",
        folderId: "act-two",
        position: 1,
      },
      {
        id: "item-c-arrival",
        kind: "chapter",
        chapterId: "c-arrival",
        parentFolderId: "act-one",
        position: 0,
      },
      {
        id: "item-c-archive",
        kind: "chapter",
        chapterId: "c-archive",
        parentFolderId: "act-one",
        position: 1,
      },
      {
        id: "item-c-storm",
        kind: "chapter",
        chapterId: "c-storm",
        parentFolderId: "act-two",
        position: 0,
      },
      {
        id: "item-c-crossing",
        kind: "chapter",
        chapterId: "c-crossing",
        parentFolderId: "act-two",
        position: 1,
      },
    ],
  },
};

export const figures = {
  nodes: [
    {
      id: "mara",
      x: 80,
      y: 80,
      type: "person",
      name: "Mara Venn",
      label: "Kartographin",
      sub: "Liest Veränderungen in lebenden Karten.",
      accent: "gold",
      important: true,
      profile: {
        notes:
          "Mara Venn\nKartographin zwischen Pflicht und Neugier.\n\nWas sie antreibt\nMara will herausfinden, weshalb die Karten ihres Vaters eine Küste zeigen, die es nicht geben dürfte.\n\nSpuren im Nordhafen\nIven Rook kennt den Zugang zum Gezeitenarchiv. Er hilft ihr bei der Öffnung des Atlas, verschweigt aber seine Verbindung zur Gilde.\n\nOffene Frage\nWird sie ihm vertrauen, wenn die letzte sichere Route verschwindet?",
        fields: [
          {
            id: "field-mara",
            key: "Rolle",
            value: "Kartographin",
          },
          {
            id: "mara-origin",
            key: "Herkunft",
            value: "Nordhafen",
          },
        ],
        noteMarks: [
          {
            from: 0,
            to: 9,
            kind: "heading",
            level: 1,
          },
          {
            from: 54,
            to: 70,
            kind: "heading",
            level: 2,
          },
          {
            from: 174,
            to: 193,
            kind: "heading",
            level: 2,
          },
          {
            from: 327,
            to: 339,
            kind: "heading",
            level: 2,
          },
        ],
        noteReferences: [
          {
            id: "ref-iven",
            target: {
              kind: "entity",
              id: "iven",
            },
            from: 194,
            to: 203,
            surface: "Iven Rook",
          },
          {
            id: "ref-archive",
            target: {
              kind: "place",
              id: "archiv",
            },
            from: 225,
            to: 239,
            surface: "Gezeitenarchiv",
          },
          {
            id: "ref-atlas-open",
            target: {
              kind: "timeline",
              id: "t2",
            },
            from: 262,
            to: 279,
            surface: "Öffnung des Atlas",
          },
        ],
      },
      aliases: [
        {
          alias: "Die Kartenleserin",
          source: "manual",
        },
      ],
    },
    {
      id: "iven",
      x: 640,
      y: 80,
      type: "person",
      name: "Iven Rook",
      label: "Archivar",
      sub: "Bewahrt die verbotenen Küstenkarten.",
      accent: "rose",
      profile: {
        notes: "Bewahrt die verbotenen Küstenkarten.",
        fields: [
          {
            id: "field-iven",
            key: "Rolle",
            value: "Archivar",
          },
        ],
      },
    },
    {
      id: "gilde",
      x: 1200,
      y: 80,
      type: "organisation",
      name: "Kartographengilde",
      label: "Organisation",
      sub: "Kontrolliert die offiziellen Seewege.",
      accent: "ink",
      profile: {
        notes: "Kontrolliert die offiziellen Seewege.",
        fields: [
          {
            id: "field-gilde",
            key: "Rolle",
            value: "Organisation",
          },
        ],
      },
    },
    {
      id: "archiv",
      x: 640,
      y: 410,
      type: "ort",
      name: "Gezeitenarchiv",
      label: "Ort",
      sub: "Ein gläserner Bau direkt über dem Wasser.",
      accent: "moss",
      profile: {
        notes: "Ein gläserner Bau direkt über dem Wasser.",
        fields: [
          {
            id: "field-archiv",
            key: "Rolle",
            value: "Ort",
          },
        ],
      },
      mapX: 220,
      mapY: 260,
    },
    {
      id: "leuchtturm",
      x: 1200,
      y: 410,
      type: "ort",
      name: "Leuchtturmklippe",
      label: "Ort",
      sub: "Letzter fester Punkt vor dem Kartennebel.",
      accent: "ink",
      profile: {
        notes: "Letzter fester Punkt vor dem Kartennebel.",
        fields: [
          {
            id: "field-leuchtturm",
            key: "Rolle",
            value: "Ort",
          },
        ],
      },
      mapX: 860,
      mapY: 520,
    },
    {
      id: "atlas",
      x: 80,
      y: 410,
      type: "objekt",
      name: "Der gläserne Atlas",
      label: "Artefakt",
      sub: "Seine Linien reagieren auf kommende Entscheidungen.",
      accent: "gold",
      important: true,
      profile: {
        notes: "Seine Linien reagieren auf kommende Entscheidungen.",
        fields: [
          {
            id: "field-atlas",
            key: "Rolle",
            value: "Artefakt",
          },
        ],
      },
    },
    {
      id: "lumen",
      x: 640,
      y: 740,
      type: "tier",
      name: "Lumen",
      label: "Küstenvogel",
      sub: "Findet Wege durch den Kartennebel.",
      accent: "moss",
      profile: {
        notes: "Findet Wege durch den Kartennebel.",
        fields: [
          {
            id: "field-lumen",
            key: "Rolle",
            value: "Küstenvogel",
          },
        ],
      },
    },
  ],
  edges: [
    {
      id: "e1",
      from: "mara",
      to: "iven",
      label: "misstraut",
      directed: true,
      versions: [
        {
          momentId: "t2",
          label: "arbeitet mit",
          active: true,
        },
        {
          momentId: "t3",
          label: "vertraut",
          active: true,
        },
      ],
      lineStyle: "solid",
    },
    {
      id: "e2",
      from: "mara",
      to: "atlas",
      label: "trägt",
      directed: true,
      lineStyle: "solid",
      color: "gold",
    },
    {
      id: "e3",
      from: "iven",
      to: "archiv",
      label: "hütet",
      directed: true,
      lineStyle: "solid",
    },
    {
      id: "e4",
      from: "gilde",
      to: "iven",
      label: "beauftragt",
      directed: true,
      versions: [
        {
          momentId: "t3",
          label: "verfolgt",
          active: true,
          color: "rose",
        },
      ],
      lineStyle: "dashed",
    },
    {
      id: "e5",
      from: "mara",
      to: "lumen",
      label: "verbunden",
      directed: false,
      lineStyle: "solid",
    },
    {
      id: "e6",
      from: "atlas",
      to: "gilde",
      label: "beansprucht",
      directed: true,
      lineStyle: "dashed",
    },
  ],
  timeline: [
    {
      id: "t1",
      title: "Ankunft im Nordhafen",
      note: "Mara erreicht die Stadt und sucht das Archiv.",
      time: 0,
      position: 0,
      precision: "day",
    },
    {
      id: "t2",
      title: "Öffnung des Atlas",
      note: "Die erste verborgene Route erscheint.",
      time: 3,
      position: 1,
      precision: "day",
    },
    {
      id: "t3",
      title: "Bruch mit der Gilde",
      note: "Die Gilde erklärt Iven und Mara zu Verrätern.",
      time: 8,
      position: 2,
      precision: "day",
    },
    {
      id: "t4",
      title: "Die Überfahrt",
      note: "Aufbruch durch den Kartennebel.",
      time: 11,
      position: 3,
      precision: "day",
    },
  ],
  timeSystem: {
    id: "nordhafen-calendar",
    name: "Kalender von Nordhafen",
    kind: "gregorian",
    unit: "day",
    epochTime: 0,
    epochYear: 1847,
    epochMonth: 9,
    epochDay: 3,
    epochWeekday: 0,
    eraName: "",
    eraAbbreviation: "",
    displayFormat: "",
    months: [],
    weekdays: [],
  },
  mapScale: {
    unitsPer100px: 0.5,
    unitLabel: "km",
  },
  presence: [
    {
      id: "presence-mara-one",
      elementId: "mara",
      placeId: "archiv",
      momentId: "t1",
    },
    {
      id: "presence-iven-one",
      elementId: "iven",
      placeId: "archiv",
      momentId: "t1",
    },
    {
      id: "presence-mara-two",
      elementId: "mara",
      placeId: "leuchtturm",
      momentId: "t4",
    },
    {
      id: "presence-iven-two",
      elementId: "iven",
      placeId: "leuchtturm",
      momentId: "t4",
    },
  ],
};

export const storyboards = {
  boards: [
    {
      id: "main-storyboard",
      title: "Der Weg durch den Nebel",
    },
    {
      id: "second-board",
      title: "Die Überfahrt",
    },
  ],
  nodes: [
    {
      id: "group-act-one",
      boardId: "main-storyboard",
      kind: "group",
      label: "I · Nordhafen",
      text: "Vom ersten Hinweis zum gemeinsamen Aufbruch.",
      x: 30,
      y: 30,
      width: 1140,
      height: 620,
      zIndex: 0,
    },
    {
      id: "note-arrival",
      boardId: "main-storyboard",
      kind: "note",
      label: "Ankunft & erste Spur",
      text: "Ein fremder Hafen, eine lebende Karte.\n\nMara Venn sucht im Gezeitenarchiv nach dem Nachlass ihres Vaters.",
      x: 70,
      y: 190,
      width: 330,
      height: 190,
      zIndex: 1,
      noteReferences: [
        {
          id: "story-ref-mara",
          target: {
            kind: "entity",
            id: "mara",
          },
          from: 40,
          to: 49,
          surface: "Mara Venn",
        },
        {
          id: "story-ref-archive",
          target: {
            kind: "place",
            id: "archiv",
          },
          from: 59,
          to: 73,
          surface: "Gezeitenarchiv",
        },
      ],
    },
    {
      id: "reference-mara",
      boardId: "main-storyboard",
      kind: "reference",
      target: {
        kind: "entity",
        id: "mara",
      },
      label: "Mara Venn",
      text: "Was weiß sie über die Karten?",
      x: 480,
      y: 190,
      width: 240,
      height: 170,
      zIndex: 1,
    },
    {
      id: "reference-archive",
      boardId: "main-storyboard",
      kind: "reference",
      target: {
        kind: "place",
        id: "archiv",
      },
      label: "Gezeitenarchiv",
      text: "Hier beginnt die Suche.",
      x: 840,
      y: 190,
      width: 270,
      height: 170,
      zIndex: 1,
    },
    {
      id: "note-turn",
      boardId: "main-storyboard",
      kind: "note",
      label: "Wendepunkt",
      text: "Die Gilde sperrt den Hafen.\n\nAus einer Suche nach Antworten wird die Entscheidung, gemeinsam aufzubrechen.",
      x: 70,
      y: 430,
      width: 330,
      height: 180,
      zIndex: 1,
    },
    {
      id: "reference-chapter",
      boardId: "main-storyboard",
      kind: "reference",
      target: {
        kind: "chapter",
        id: "c-storm",
      },
      label: "Vor dem Sturm",
      text: "Die Entscheidung zur Flucht.",
      x: 480,
      y: 430,
      width: 240,
      height: 180,
      zIndex: 1,
    },
    {
      id: "board-crossing",
      boardId: "main-storyboard",
      kind: "storyboard",
      target: {
        kind: "storyboard",
        id: "second-board",
      },
      label: "II · Die Überfahrt",
      text: "Aufbruch ins Unbekannte.",
      x: 840,
      y: 430,
      width: 270,
      height: 180,
      zIndex: 1,
    },
    {
      id: "note-sea",
      boardId: "second-board",
      kind: "note",
      label: "Jenseits der bekannten Küste",
      text: "Welche Linien bleiben auf dem Atlas, wenn das Land hinter ihnen verschwindet?",
      x: 120,
      y: 120,
      width: 360,
      height: 220,
    },
  ],
  edges: [
    {
      id: "board-edge-one",
      boardId: "main-storyboard",
      sourceNodeId: "note-arrival",
      targetNodeId: "reference-mara",
      label: "Figur",
      directed: true,
    },
    {
      id: "board-edge-two",
      boardId: "main-storyboard",
      sourceNodeId: "reference-mara",
      targetNodeId: "reference-archive",
      label: "sucht Antworten",
      directed: true,
    },
    {
      id: "board-edge-three",
      boardId: "main-storyboard",
      sourceNodeId: "note-turn",
      targetNodeId: "reference-chapter",
      directed: true,
    },
    {
      id: "board-edge-four",
      boardId: "main-storyboard",
      sourceNodeId: "reference-chapter",
      targetNodeId: "board-crossing",
      label: "Aufbruch",
      directed: true,
    },
  ],
};
