"""Ports required by world catalogue use cases."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol

from quiltor.application.worlds.types import OpenedWorld, WorldPaths, WorldSummary


class WorldRepository(Protocol):
    @property
    def data_directory(self) -> Path: ...

    @property
    def worlds_directory(self) -> Path: ...

    def prepare(self) -> None: ...
    def is_valid_id(self, world_id: str) -> bool: ...
    def list(self, owner_sub: str | None = None) -> list[WorldSummary]: ...
    def create(self, title: str, backup_url: str, owner_sub: str) -> WorldSummary: ...
    def open(self, world_id: str, owner_sub: str | None = None) -> OpenedWorld: ...
    def paths_for(self, world_id: str) -> WorldPaths: ...
    def delete(self, world_id: str, owner_sub: str) -> None: ...
    def assign_owner(self, world_id: str, owner_sub: str) -> None: ...
    def finalize_restore(
        self, world_id: str, owner_sub: str, previous_revisions: dict[str, int]
    ) -> None: ...


__all__ = ["WorldRepository"]
